apiVersion: apps/v1
kind: Deployment
metadata:
  name: brb
  labels:
    app-label: brb-label
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app-label: brb-label
  template:
    metadata:
      labels:
        app-label: brb-label
    spec:
      containers:
        - name: brb-app
          image: brb:v14
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      imagePullSecrets:
        - name: imsecret