// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: brbdxrpb/brbdxrpb.proto

package brbdxrpb

import (
	_ "github.com/filecoin-project/mir/pkg/pb/mir"
	_ "github.com/filecoin-project/mir/pkg/pb/net"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*Message_StartMessage
	//	*Message_EchoMessage
	//	*Message_ReadyMessage
	Type isMessage_Type `protobuf_oneof:"type"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brbdxrpb_brbdxrpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_brbdxrpb_brbdxrpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_brbdxrpb_brbdxrpb_proto_rawDescGZIP(), []int{0}
}

func (m *Message) GetType() isMessage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Message) GetStartMessage() *StartMessage {
	if x, ok := x.GetType().(*Message_StartMessage); ok {
		return x.StartMessage
	}
	return nil
}

func (x *Message) GetEchoMessage() *EchoMessage {
	if x, ok := x.GetType().(*Message_EchoMessage); ok {
		return x.EchoMessage
	}
	return nil
}

func (x *Message) GetReadyMessage() *ReadyMessage {
	if x, ok := x.GetType().(*Message_ReadyMessage); ok {
		return x.ReadyMessage
	}
	return nil
}

type isMessage_Type interface {
	isMessage_Type()
}

type Message_StartMessage struct {
	StartMessage *StartMessage `protobuf:"bytes,1,opt,name=start_message,json=startMessage,proto3,oneof"`
}

type Message_EchoMessage struct {
	EchoMessage *EchoMessage `protobuf:"bytes,2,opt,name=echo_message,json=echoMessage,proto3,oneof"`
}

type Message_ReadyMessage struct {
	ReadyMessage *ReadyMessage `protobuf:"bytes,3,opt,name=ready_message,json=readyMessage,proto3,oneof"`
}

func (*Message_StartMessage) isMessage_Type() {}

func (*Message_EchoMessage) isMessage_Type() {}

func (*Message_ReadyMessage) isMessage_Type() {}

type StartMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	N    int64  `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StartMessage) Reset() {
	*x = StartMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brbdxrpb_brbdxrpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMessage) ProtoMessage() {}

func (x *StartMessage) ProtoReflect() protoreflect.Message {
	mi := &file_brbdxrpb_brbdxrpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMessage.ProtoReflect.Descriptor instead.
func (*StartMessage) Descriptor() ([]byte, []int) {
	return file_brbdxrpb_brbdxrpb_proto_rawDescGZIP(), []int{1}
}

func (x *StartMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StartMessage) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *StartMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EchoMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	N     int64  `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	Hash  []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Chunk []byte `protobuf:"bytes,4,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *EchoMessage) Reset() {
	*x = EchoMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brbdxrpb_brbdxrpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoMessage) ProtoMessage() {}

func (x *EchoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_brbdxrpb_brbdxrpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoMessage.ProtoReflect.Descriptor instead.
func (*EchoMessage) Descriptor() ([]byte, []int) {
	return file_brbdxrpb_brbdxrpb_proto_rawDescGZIP(), []int{2}
}

func (x *EchoMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EchoMessage) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *EchoMessage) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *EchoMessage) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type ReadyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	N     int64  `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	Hash  []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Chunk []byte `protobuf:"bytes,4,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *ReadyMessage) Reset() {
	*x = ReadyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brbdxrpb_brbdxrpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyMessage) ProtoMessage() {}

func (x *ReadyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_brbdxrpb_brbdxrpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyMessage.ProtoReflect.Descriptor instead.
func (*ReadyMessage) Descriptor() ([]byte, []int) {
	return file_brbdxrpb_brbdxrpb_proto_rawDescGZIP(), []int{3}
}

func (x *ReadyMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReadyMessage) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *ReadyMessage) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ReadyMessage) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_brbdxrpb_brbdxrpb_proto protoreflect.FileDescriptor

var file_brbdxrpb_brbdxrpb_proto_rawDesc = []byte{
	0x0a, 0x17, 0x62, 0x72, 0x62, 0x64, 0x78, 0x72, 0x70, 0x62, 0x2f, 0x62, 0x72, 0x62, 0x64, 0x78,
	0x72, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x62, 0x72, 0x62, 0x64, 0x78,
	0x72, 0x70, 0x62, 0x1a, 0x1c, 0x6d, 0x69, 0x72, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e,
	0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1c, 0x6e, 0x65, 0x74, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x65,
	0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xd7, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x72, 0x62, 0x64, 0x78, 0x72, 0x70, 0x62, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x65, 0x63,
	0x68, 0x6f, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x62, 0x72, 0x62, 0x64, 0x78, 0x72, 0x70, 0x62, 0x2e, 0x45, 0x63, 0x68, 0x6f,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x65, 0x63, 0x68, 0x6f, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x72, 0x65, 0x61, 0x64, 0x79, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x62, 0x72, 0x62, 0x64, 0x78, 0x72, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x79, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x3a, 0x04, 0xc8, 0xe4, 0x1d, 0x01, 0x42, 0x0c, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x04, 0xc8, 0xe4, 0x1d, 0x01, 0x22, 0x46, 0x0a, 0x0c, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x3a, 0x04, 0xd0, 0xe4, 0x1d,
	0x01, 0x22, 0x5b, 0x0a, 0x0b, 0x45, 0x63, 0x68, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x3a, 0x04, 0xd0, 0xe4, 0x1d, 0x01, 0x22, 0x5c,
	0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c,
	0x0a, 0x01, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x3a, 0x04, 0xd0, 0xe4, 0x1d, 0x01, 0x42, 0x31, 0x5a, 0x2f,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x63,
	0x6f, 0x69, 0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6d, 0x69, 0x72, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x72, 0x62, 0x64, 0x78, 0x72, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_brbdxrpb_brbdxrpb_proto_rawDescOnce sync.Once
	file_brbdxrpb_brbdxrpb_proto_rawDescData = file_brbdxrpb_brbdxrpb_proto_rawDesc
)

func file_brbdxrpb_brbdxrpb_proto_rawDescGZIP() []byte {
	file_brbdxrpb_brbdxrpb_proto_rawDescOnce.Do(func() {
		file_brbdxrpb_brbdxrpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_brbdxrpb_brbdxrpb_proto_rawDescData)
	})
	return file_brbdxrpb_brbdxrpb_proto_rawDescData
}

var file_brbdxrpb_brbdxrpb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_brbdxrpb_brbdxrpb_proto_goTypes = []interface{}{
	(*Message)(nil),      // 0: brbdxrpb.Message
	(*StartMessage)(nil), // 1: brbdxrpb.StartMessage
	(*EchoMessage)(nil),  // 2: brbdxrpb.EchoMessage
	(*ReadyMessage)(nil), // 3: brbdxrpb.ReadyMessage
}
var file_brbdxrpb_brbdxrpb_proto_depIdxs = []int32{
	1, // 0: brbdxrpb.Message.start_message:type_name -> brbdxrpb.StartMessage
	2, // 1: brbdxrpb.Message.echo_message:type_name -> brbdxrpb.EchoMessage
	3, // 2: brbdxrpb.Message.ready_message:type_name -> brbdxrpb.ReadyMessage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_brbdxrpb_brbdxrpb_proto_init() }
func file_brbdxrpb_brbdxrpb_proto_init() {
	if File_brbdxrpb_brbdxrpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_brbdxrpb_brbdxrpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brbdxrpb_brbdxrpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brbdxrpb_brbdxrpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brbdxrpb_brbdxrpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_brbdxrpb_brbdxrpb_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Message_StartMessage)(nil),
		(*Message_EchoMessage)(nil),
		(*Message_ReadyMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_brbdxrpb_brbdxrpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_brbdxrpb_brbdxrpb_proto_goTypes,
		DependencyIndexes: file_brbdxrpb_brbdxrpb_proto_depIdxs,
		MessageInfos:      file_brbdxrpb_brbdxrpb_proto_msgTypes,
	}.Build()
	File_brbdxrpb_brbdxrpb_proto = out.File
	file_brbdxrpb_brbdxrpb_proto_rawDesc = nil
	file_brbdxrpb_brbdxrpb_proto_goTypes = nil
	file_brbdxrpb_brbdxrpb_proto_depIdxs = nil
}
